language: ruby
sudo: false
cache: bundler
install: true
before_install: gem install bundler -v 1.11.2
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-9.0.5.0
  - jruby-head
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.0.5.0
